# Generated by Django 4.1.7 on 2023-08-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('product_image_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item_id', models.CharField(max_length=50)),
                ('stock_keeping_unit', models.CharField(max_length=100)),
                ('quantity_in_stock', models.IntegerField()),
                ('product_image_url', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('parent_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.ManyToManyField(max_length=50, to='products.productitem'),
        ),
    ]
